### ISSUE TITLE
Переделать тесты

### ISSUE THREAD

**Issue by nimmortal** [nimmortal/WikiFilms#6]
Надо переделать тесты, а именно убрать вообще очистку базы и переписать под новые колонки в базе. Надо быть очень аккуратным, чтобы ничего впредь не стирать.

**Comment by nimmortal** [comment]
Немного подправил тест на фильмы, пока один.
Не получается организовать транзакцию, похоже, что на голом jdbc этого не сделать.
Но тест теперь валиден, таким образом можно править остальные, главное создать совсем глупые тестовые данные, чтобы они никак не пересеклись с основными.

**Comment by VitBuk** [comment]
Сделано
